
- name: Ethereum Pairty nodes
  hosts: parity-nodes
  remote_user: root
  vars:
    - parity_extra_args: "--jsonrpc-interface all --jsonrpc-apis web3 --no-dapps"
  roles:
    - ethereum-parity

- name: Go-Ethereum nodes
  hosts: geth-nodes
  remote_user: root
  vars:
    - geth_extra_args: "--cache 1024 --fast --rpc --rpcaddr 0.0.0.0 --rpcapi eth,net,web3"
  roles:
    - ethereum-geth