- name: Check requirements
  assert:
    that:
      - ansible_distribution == 'Ubuntu'

- name: repositories
  apt_repository: repo="{{ item }}"
  tags: packages
  with_items:
    - ppa:ethereum/ethereum

- name: packages
  apt: name={{ item }} state=present
  tags: packages
  with_items:
    - software-properties-common
    - geth
