---
- include: install-ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  tags: packages

- include: install-other.yml
  when: ansible_distribution != 'Ubuntu'
  tags: packages

- group: name={{ geth_group }} system=yes state=present
- user: name={{ geth_user }} group={{ geth_group }} home={{ geth_home }} shell=/bin/false state=present

- name: "systemd geth service configuration file"
  template: src=templates/geth.service.j2 dest=/etc/systemd/system/{{ systemd_service_name }}.service owner=root group=root mode=0644
  notify:
    - reload systemd
    - stop geth

- meta: flush_handlers

- name: "service geth enabled"
  service: name={{ systemd_service_name }} enabled=yes state=started

- name: "monitoring"
  include: monitoring.yml
  when: icinga_server is defined
  tags: monitoring