---
- name: "service geth stopped"
  service: name={{ systemd_service_name }} enabled=no state=stopped
  ignore_errors: yes

- name: "uninstall package"
  apt: name=geth state=absent
  when: ansible_distribution == 'Ubuntu'

- name: "remove geth bin"
  file:
    path: "{{ geth_bindir }}/geth"
    state: absent

- name: "remove systemd geth service configuration file"
  file: path=/etc/systemd/system/{{ systemd_service_name }}.service state=absent
  notify:
    - reload systemd

- meta: flush_handlers

- user: name={{ geth_user }} state=absent
- group: name={{ geth_group }} state=absent

- name: "delete geth home"
  file:
    path: "{{ geth_home }}/"
    state: absent

- name: "remove nrpe config"
  file: path="/etc/nagios/nrpe.d/{{ systemd_service_name }}.cfg" state=absent
  notify:
    - restart nrpe
