---
parity_user: parity
parity_group: parity
parity_dst_bindir: /usr/bin
parity_home: /var/lib/parity
parity_disabled: false
#parity_source: http://localhost:8080/ipfs/parity
#parity_sum: sha256:1312a245f9e0cfd0922dac385f5ee8f6a1e16f30161e34f034a1588f4c8d3ec7
parity_extra_args:
#parity_extra_args: "--db-compaction hdd --nat none
